import type { MemberBenefit, MemberRecord, MembershipPlan } from "./types";

export const membershipPlans: MembershipPlan[] = [
  {
    id: "gold",
    name: "Gold Tier",
    inclusions: [
      { id: "gold-units", label: "15 anti-wrinkle units monthly" },
      { id: "gold-peel", label: "1x chemical peel monthly" },
      { id: "gold-retail", label: "10% off skincare retail" },
    ],
    patients: 22,
    monthlyPrice: 349,
    isActive: true,
    minimumCommitmentMonths: 3,
    noticePeriodDays: 30,
    cancellationFee: 99,
  },
  {
    id: "silver",
    name: "Silver Tier",
    inclusions: [
      { id: "silver-units", label: "10 anti-wrinkle units monthly" },
      { id: "silver-facial", label: "1x express facial monthly" },
      { id: "silver-retail", label: "5% off skincare retail" },
    ],
    patients: 27,
    monthlyPrice: 229,
    isActive: true,
    minimumCommitmentMonths: 2,
    noticePeriodDays: 21,
    cancellationFee: 49,
  },
  {
    id: "bronze",
    name: "Bronze Tier",
    inclusions: [
      { id: "bronze-injectables", label: "10% off injectables" },
      { id: "bronze-led", label: "1x LED session monthly" },
      { id: "bronze-priority", label: "Priority booking access" },
    ],
    patients: 18,
    monthlyPrice: 149,
    isActive: true,
    minimumCommitmentMonths: 1,
    noticePeriodDays: 14,
    cancellationFee: 0,
  },
];

type MemberSeed = Omit<MemberRecord, "planName" | "benefits"> & {
  benefits: MemberBenefit[];
};

const memberSeeds: MemberSeed[] = [
  {
    id: "member-1",
    patientName: "Emma Clarke",
    email: "emma.clarke@example.com",
    planId: "gold",
    membershipStatus: "active",
    nextPaymentDate: "15 Mar 2026",
    paidToDate: 2094,
    term: "6/12 months",
    membershipStartDate: "15 Sep 2025",
    membershipEndDate: "15 Sep 2026",
    renewalDate: "15 Apr 2026",
    additionalRevenue: 1840,
    lifetimeValue: 3934,
    cardOnFile: {
      brand: "Visa",
      last4: "4242",
      expiry: "08/28",
    },
    pausedUntil: null,
    benefits: [
      {
        id: "member-1-benefit-1",
        inclusionId: "gold-units",
        kind: "banked-units",
        carryover: "accrues",
        summary: "15 units accrue monthly and carry forward until used.",
        detail: "Last visit was 3 months ago, so Emma has built up 45 units available.",
        available: "45 units available",
        used: "0 units used this cycle",
        nextReset: "No expiry while membership stays active",
        lastRedeemedDate: null,
      },
      {
        id: "member-1-benefit-2",
        inclusionId: "gold-peel",
        kind: "monthly-inclusion",
        carryover: "resets",
        summary: "1 treatment per cycle. Unused entitlement resets at renewal.",
        detail: "Redeemed for the current cycle. Becomes available again on 15 Apr 2026.",
        available: "Used this cycle",
        used: "1 of 1 redeemed",
        nextReset: "Renews 15 Apr 2026",
        lastRedeemedDate: "02 Mar 2026",
      },
      {
        id: "member-1-benefit-3",
        inclusionId: "gold-retail",
        kind: "discount",
        carryover: "non-stacking",
        summary: "10% off active at every eligible checkout.",
        detail: "Discounts do not stack or accumulate. The member either has it or does not.",
        available: "10% active",
        nextReset: "Applies while membership is active",
        lastRedeemedDate: "21 Feb 2026",
      },
    ],
    activity: [
      {
        id: "member-1-activity-1",
        type: "benefit",
        title: "Chemical peel redeemed",
        description: "March inclusion used. Renews again on 15 Apr 2026.",
        date: "02 Mar 2026",
      },
      {
        id: "member-1-activity-2",
        type: "additional-payment",
        title: "Skin booster purchased",
        description: "Standalone treatment outside membership.",
        date: "21 Feb 2026",
        amount: 690,
      },
      {
        id: "member-1-activity-3",
        type: "membership-payment",
        title: "Gold Tier membership charged",
        description: "Monthly membership payment collected.",
        date: "15 Feb 2026",
        amount: 349,
      },
    ],
  },
  {
    id: "member-2",
    patientName: "Sophie Nguyen",
    email: "sophie.nguyen@example.com",
    planId: "silver",
    membershipStatus: "active",
    nextPaymentDate: "20 Mar 2026",
    paidToDate: 687,
    term: "3/12 months",
    membershipStartDate: "20 Dec 2025",
    membershipEndDate: "20 Sep 2026",
    renewalDate: "20 Apr 2026",
    additionalRevenue: 410,
    lifetimeValue: 1097,
    cardOnFile: {
      brand: "Mastercard",
      last4: "1488",
      expiry: "11/27",
    },
    pausedUntil: null,
    benefits: [
      {
        id: "member-2-benefit-1",
        inclusionId: "silver-units",
        kind: "banked-units",
        carryover: "accrues",
        summary: "10 units accrue monthly and carry forward until used.",
        detail: "Sophie missed one cycle, so she has 20 units banked for the next visit.",
        available: "20 units available",
        used: "0 units used this cycle",
        nextReset: "No expiry while membership stays active",
        lastRedeemedDate: null,
      },
      {
        id: "member-2-benefit-2",
        inclusionId: "silver-facial",
        kind: "monthly-inclusion",
        carryover: "resets",
        summary: "1 treatment per cycle with no carryover.",
        detail: "Redeemed this cycle. Next facial becomes available on 20 Apr 2026.",
        available: "Used this cycle",
        used: "1 of 1 redeemed",
        nextReset: "Renews 20 Apr 2026",
        lastRedeemedDate: "05 Mar 2026",
      },
      {
        id: "member-2-benefit-3",
        inclusionId: "silver-retail",
        kind: "discount",
        carryover: "non-stacking",
        summary: "5% off active at eligible retail checkout.",
        detail: "Discount remains active but cannot accumulate into a larger discount later.",
        available: "5% active",
        nextReset: "Applies while membership is active",
        lastRedeemedDate: "06 Feb 2026",
      },
    ],
    activity: [
      {
        id: "member-2-activity-1",
        type: "benefit",
        title: "Express facial redeemed",
        description: "March inclusion booked. Renews again on 20 Apr 2026.",
        date: "05 Mar 2026",
      },
      {
        id: "member-2-activity-2",
        type: "membership-payment",
        title: "Silver Tier membership charged",
        description: "Monthly membership payment collected.",
        date: "20 Feb 2026",
        amount: 229,
      },
      {
        id: "member-2-activity-3",
        type: "additional-payment",
        title: "Retail skincare purchase",
        description: "Post-appointment product sale.",
        date: "06 Feb 2026",
        amount: 220,
      },
    ],
  },
  {
    id: "member-3",
    patientName: "Olivia Hart",
    email: "olivia.hart@example.com",
    planId: "bronze",
    membershipStatus: "paused",
    nextPaymentDate: "04 Apr 2026",
    paidToDate: 149,
    term: "Ongoing",
    membershipStartDate: "04 Feb 2026",
    membershipEndDate: null,
    renewalDate: "04 May 2026",
    additionalRevenue: 1240,
    lifetimeValue: 1389,
    cardOnFile: {
      brand: "Amex",
      last4: "3005",
      expiry: "03/27",
    },
    pausedUntil: "04 May 2026",
    benefits: [
      {
        id: "member-3-benefit-1",
        inclusionId: "bronze-injectables",
        kind: "discount",
        carryover: "non-stacking",
        summary: "10% off injectables at checkout.",
        detail: "This is an active pricing rule, not a stored balance.",
        available: "10% active",
        nextReset: "Applies while membership is active",
        lastRedeemedDate: "01 Mar 2026",
      },
      {
        id: "member-3-benefit-2",
        inclusionId: "bronze-led",
        kind: "monthly-inclusion",
        carryover: "resets",
        summary: "1 session per cycle with no carryover.",
        detail: "Already used for the current cycle and will re-open on 04 May 2026.",
        available: "Used this cycle",
        used: "1 of 1 redeemed",
        nextReset: "Renews 04 May 2026",
        lastRedeemedDate: "18 Feb 2026",
      },
      {
        id: "member-3-benefit-3",
        inclusionId: "bronze-priority",
        kind: "perk",
        carryover: "non-stacking",
        summary: "Operational perk available on every booking.",
        detail: "Always on while the member is active; nothing to redeem or bank.",
        available: "Active perk",
        nextReset: "Applies while membership is active",
        lastRedeemedDate: null,
      },
    ],
    activity: [
      {
        id: "member-3-activity-1",
        type: "additional-payment",
        title: "Lip volumisation treatment",
        description: "Standalone injectable service.",
        date: "01 Mar 2026",
        amount: 890,
      },
      {
        id: "member-3-activity-2",
        type: "benefit",
        title: "LED session redeemed",
        description: "First monthly inclusion used. Renews again on 04 May 2026.",
        date: "18 Feb 2026",
      },
      {
        id: "member-3-activity-3",
        type: "membership-payment",
        title: "Bronze Tier membership charged",
        description: "Monthly membership payment collected.",
        date: "04 Feb 2026",
        amount: 149,
      },
    ],
  },
  {
    id: "member-4",
    patientName: "Mia Bennett",
    email: "mia.bennett@example.com",
    planId: "gold",
    membershipStatus: "active",
    nextPaymentDate: "28 Mar 2026",
    paidToDate: 3839,
    term: "11/12 months",
    membershipStartDate: "28 Apr 2025",
    membershipEndDate: "28 Apr 2026",
    renewalDate: "28 Apr 2026",
    additionalRevenue: 3160,
    lifetimeValue: 6999,
    cardOnFile: {
      brand: "Visa",
      last4: "8821",
      expiry: "01/29",
    },
    pausedUntil: null,
    benefits: [
      {
        id: "member-4-benefit-1",
        inclusionId: "gold-units",
        kind: "banked-units",
        carryover: "accrues",
        summary: "15 units accrue monthly and carry forward until used.",
        detail: "Mia has skipped two visits, so she has 30 units available going into her next consult.",
        available: "30 units available",
        used: "15 units used last cycle",
        nextReset: "No expiry while membership stays active",
        lastRedeemedDate: "10 Jan 2026",
      },
      {
        id: "member-4-benefit-2",
        inclusionId: "gold-peel",
        kind: "monthly-inclusion",
        carryover: "resets",
        summary: "1 treatment per cycle. Unused entitlement resets at renewal.",
        detail: "Current cycle peel has been used. Next one opens when the cycle renews.",
        available: "Used this cycle",
        used: "1 of 1 redeemed",
        nextReset: "Renews 28 Apr 2026",
        lastRedeemedDate: "27 Feb 2026",
      },
      {
        id: "member-4-benefit-3",
        inclusionId: "gold-retail",
        kind: "discount",
        carryover: "non-stacking",
        summary: "10% off active at every eligible checkout.",
        detail: "Discount is active now but never accumulates beyond the plan benefit.",
        available: "10% active",
        nextReset: "Applies while membership is active",
        lastRedeemedDate: "10 Feb 2026",
      },
    ],
    activity: [
      {
        id: "member-4-activity-1",
        type: "benefit",
        title: "Chemical peel redeemed",
        description: "Current benefit cycle used. Renews on 28 Apr 2026 with plan term review.",
        date: "27 Feb 2026",
      },
      {
        id: "member-4-activity-2",
        type: "additional-payment",
        title: "Broadband light treatment",
        description: "Additional treatment added at checkout.",
        date: "10 Feb 2026",
        amount: 960,
      },
      {
        id: "member-4-activity-3",
        type: "membership-payment",
        title: "Gold Tier membership charged",
        description: "Monthly membership payment collected.",
        date: "28 Jan 2026",
        amount: 349,
      },
    ],
  },
  {
    id: "member-5",
    patientName: "Charlotte Reed",
    email: "charlotte.reed@example.com",
    planId: "silver",
    membershipStatus: "cancelled",
    nextPaymentDate: "No upcoming payment",
    paidToDate: 916,
    term: "Cancelled",
    membershipStartDate: "12 Sep 2025",
    membershipEndDate: "12 Feb 2026",
    renewalDate: "12 Mar 2026",
    additionalRevenue: 780,
    lifetimeValue: 1696,
    cardOnFile: {
      brand: "Visa",
      last4: "7719",
      expiry: "09/27",
    },
    pausedUntil: null,
    benefits: [
      {
        id: "member-5-benefit-1",
        inclusionId: "silver-units",
        kind: "banked-units",
        carryover: "accrues",
        summary: "10 units accrue monthly and carry forward until used.",
        detail: "Membership has been cancelled, so no new units will accrue.",
        available: "0 units available",
        used: "All units redeemed before cancellation",
        nextReset: "No further accrual after cancellation",
        lastRedeemedDate: "02 Feb 2026",
      },
      {
        id: "member-5-benefit-2",
        inclusionId: "silver-facial",
        kind: "monthly-inclusion",
        carryover: "resets",
        summary: "1 treatment per cycle with no carryover.",
        detail: "Membership has been cancelled and this inclusion is no longer available.",
        available: "Used this cycle",
        used: "Final inclusion redeemed",
        nextReset: "No future renewal after cancellation",
        lastRedeemedDate: "28 Jan 2026",
      },
      {
        id: "member-5-benefit-3",
        inclusionId: "silver-retail",
        kind: "discount",
        carryover: "non-stacking",
        summary: "5% off active at eligible retail checkout.",
        detail: "Discount is no longer active because the membership has been cancelled.",
        available: "Inactive",
        nextReset: "No longer active",
        lastRedeemedDate: "15 Jan 2026",
      },
    ],
    activity: [
      {
        id: "member-5-activity-1",
        type: "additional-payment",
        title: "Skin consultation purchased",
        description: "Standalone service after membership cancellation.",
        date: "18 Feb 2026",
        amount: 220,
      },
      {
        id: "member-5-activity-2",
        type: "membership-payment",
        title: "Final Silver Tier membership charged",
        description: "Last recurring charge before cancellation took effect.",
        date: "12 Jan 2026",
        amount: 229,
      },
    ],
  },
];

export function getMembershipPlanById(planId: string) {
  const plan = membershipPlans.find((entry) => entry.id === planId);

  if (!plan) {
    throw new Error(`Unknown membership plan: ${planId}`);
  }

  return plan;
}

export const members: MemberRecord[] = memberSeeds.map((member) => {
  const plan = getMembershipPlanById(member.planId);

  return {
    ...member,
    planName: plan.name,
    benefits: member.benefits.map((benefit) => {
      if (!plan.inclusions.some((item) => item.id === benefit.inclusionId)) {
        throw new Error(`Unknown inclusion ${benefit.inclusionId} for plan ${plan.id}`);
      }

      return benefit;
    }),
  };
});
